# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb  
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
